### ISSUE TITLE
[QWebEngine] The app does not show content when reloading the CHMs or when starting the app empty

### ISSUE THREAD

**Issue by u-235** [gyunaev/kchmviewer#10]
# [QWebEngine] The app does not show content

The app opens an chm file and shows index, but does not show content page. The old version of the application shows these files without any problems.

## Environment

- **OS** Linux Mint 18.1 Serena with kernel Linux 4.4.0-53-generic i686 GNU/Linux
- **DE** MATE Desktop Environment 1.16.2
- **Qt 5.15.2** local build with QWebEngine support

App output:

```
QObject::connect: No such signal ViewWindow::linkClicked ( const QUrl& ) in ../../../../kchmviewer/src/viewwindowmgr.cpp:147
QObject::connect:  (receiver name: 'MainWindow')
ViewWindow::openUrl 
URL scheme handler already installed for the scheme: ms-its
URL scheme handler already installed for the scheme: epub
QObject::connect: No such signal ViewWindow::linkClicked ( const QUrl& ) in ../../../../kchmviewer/src/viewwindowmgr.cpp:147
QObject::connect:  (receiver name: 'MainWindow')
ViewWindow::openUrl ms-its://ms-its/classwx_about_dialog_info.html
value retrieved: 0
```

![screen-shot](https://user-images.githubusercontent.com/5675211/119143045-d8f43d80-ba4f-11eb-9531-ca7029f0a4a7.png)

**Comment by u-235** [comment]
Important clarification. I ran the kchmviewer without arguments and then opened a files.

**Comment by gyunaev** [comment]
Also leaving this open as it works for me.

**Comment by u-235** [comment]
This is build after meaningless changes in src/src.pro.

```diff
diff --git a/src/src.pro b/src/src.pro
index f502259..6047d60 100644
--- a/src/src.pro
+++ b/src/src.pro
@@ -40,7 +40,6 @@ SOURCES += config.cpp \
     textencodings.cpp \
     treeitem_toc.cpp \
     treeitem_index.cpp
-LIBS += -lchm -lzip
 TARGET = ../bin/kchmviewer
 CONFIG += threads \
     warn_on \
@@ -60,11 +59,9 @@ FORMS += tab_bookmarks.ui \
     toolbareditor.ui
 RESOURCES += resources/images.qrc
 
-QT += webkit \
-	xml \
+QT += xml \
     network \
     widgets \
-    webkitwidgets \
     printsupport
 
 linux-g++*:{
@@ -112,6 +109,8 @@ unix:!macx: {
     POST_TARGETDEPS += ../lib/libebook/libebook.a
 }
 
+LIBS += -lchm -lzip
+
 greaterThan(QT_MAJOR_VERSION, 4) {
     # Qt 5
     greaterThan(QT_MINOR_VERSION, 5) {

```

**Comment by u-235** [comment]
> Also leaving this open as it works for me. I can confirm the CHM file from https://wxwidgets.org/downloads/ is opening fine.

Have you tried reopening a file (or opening another file) without closing the application?

**Comment by gyunaev** [comment]
Yes, and everything worked fine.

**Comment by gyunaev** [comment]
I also don't have those:

````
URL scheme handler already installed for the scheme: ms-its
URL scheme handler already installed for the scheme: epub
`````

and I'm unsure where this comes from, since ViewWindow::initialize() is only called from main.cpp

**Comment by u-235** [comment]
This happens in the ViewWindow constructor.

```cpp
    // Use our network emulation layer. I don't know if we transfer the ownership when we install it,
    // so we create one per page. May be unnecessary.    m_provider = new DataProvider_QWebEngine( this );
    page()-&gt;profile()-&gt;installUrlSchemeHandler( EBook_CHM::urlScheme(), m_provider );
    page()-&gt;profile()-&gt;installUrlSchemeHandler( EBook_EPUB::urlScheme(), m_provider );
```

**Comment by gyunaev** [comment]
Added a guard in 308a2aa..9ac73e7 - the doc now is clear the ownership isn't transferred, so one provider is enough.

**Comment by u-235** [comment]
Both reloading CHMs and opening in an empty application works fine, issue solved.
