### ISSUE TITLE
[QWebEngine] Shift+LMB and Ctrl+LMB doesn't work correctly

### ISSUE THREAD

**Issue by u-235** [gyunaev/kchmviewer#12]
Left-clicking a link with Shift or Ctrl does not open the link in a new tab, instead the link opens in the same tab.

**Comment by iDarkTemplar** [comment]
This issue should be fixed by https://github.com/gyunaev/kchmviewer/pull/13, except for dialogs. Please check.

**Comment by u-235** [comment]
Yes, #13 solves this problem.
